// FOR ASTROLOGER CONTANTS
export const astroloerContant = {
    UPDATE_ASTROLOGER_REQUEST: 'UPDATE_ASTROLOGER_REQUEST',
    UPDATE_ASTROLOGER_SUCCESS: 'UPDATE_ASTROLOGER_SUCCESS',
    UPDATE_ASTROLOGER_FAILURE: 'UPDATE_ASTROLOGER_FAILURE',
    UPDATE_ASTROLOGER_RESET: 'UPDATE_ASTROLOGER_RESET',
    GET_SINGLE_ASTROLOGER_REQUEST: 'GET_SINGLE_ASTROLOGER_REQUEST',
    GET_SINGLE_ASTROLOGER_SUCCESS: 'GET_SINGLE_ASTROLOGER_SUCCESS',
    GET_SINGLE_ASTROLOGER_FAILURE: 'GET_SINGLE_ASTROLOGER_FAILURE',
    ALL_ASTROLOGER_REQUEST: 'ALL_ASTROLOGER_REQUEST',
    ALL_ASTROLOGER_SUCCESS: 'ALL_ASTROLOGER_SUCCESS',
    ALL_ASTROLOGER_FAILURE: 'ALL_ASTROLOGER_FAILURE',
}