// BANNER CONSTANT 
export const chatContants = {
    UPDATE_CHAT_REQUEST:'UPDATE_CHAT_REQUEST',
    UPDATE_CHAT_SECCUSS:'UPDATE_CHAT_SECCUSS',
    UPDATE_CHAT_FAIL:'UPDATE_CHAT_FAIL',
    DELETE_CHAT_REQUEST:'DELETE_CHAT_REQUEST',
    DELETE_CHAT_SECCUSS:'DELETE_CHAT_SECCUSS',
    DELETE_CHAT_FAIL:'DELETE_CHAT_FAIL',
    PUSH_CHAT_REQUEST:'PUSH_CHAT_REQUEST',
    PUSH_CHAT_SUCCESS:'PUSH_CHAT_SUCCESS',
    PUSH_CHAT_FAIL:'PUSH_CHAT_FAIL',
    FETCH_CHAT_REQUEST:'FETCH_CHAT_REQUEST',
    FETCH_CHAT_SUCCESS:'FETCH_CHAT_SUCCESS',
    FETCH_CHAT_FAIL:'FETCH_CHAT_FAIL',
    UPDATE_CHAT:'UPDATE_CHAT'
}
