// BANNER CONSTANT 
export const bannerContants = {
    BANNER_REQUEST: 'BANNER_REQUEST',
    BANNER_SUCCESS: 'BANNER_SUCCESS',
    BANNER_FAILURE: 'BANNER_FAILURE',
}

// SERVICE CONSTANT
export const serviceContants = {
    SERVICE_REQUEST: 'SERVICE_REQUEST',
    SERVICE_SUCCESS: 'SERVICE_SUCCESS',
    SERVICE_FAILURE: 'SERVICE_FAILURE',
}


// ALO MALL  CONSTANT
export const alomallContants = {
    ALOMALL_REQUEST: 'ALOMALL_REQUEST',
    ALOMALL_SUCCESS: 'ALOMALL_SUCCESS',
    ALOMALL_FAILURE: 'ALOMALL_FAILURE',
}


// review
export const reviewContants = {
    CREATE_REVIEW_REQUEST: 'CREATE_REVIEW_REQUEST',
    CREATE_REVIEW_SUCCESS: 'CREATE_REVIEW_SUCCESS',
    CREATE_REVIEW_FAILURE: 'CREATE_REVIEW_FAILURE',
    REVIEW_REQUEST: 'REVIEW_REQUEST',
    REVIEW_SUCCESS: 'REVIEW_SUCCESS',
    REVIEW_FAILURE: 'REVIEW_FAILURE',
    ALL_REVIEW_REQUEST: "ALL_REVIEW_REQUEST",
    ALL_REVIEW_SUCCESS: "ALL_REVIEW_SUCCESS",
    ALL_REVIEW_FAIL: "ALL_REVIEW_FAIL",
    DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
    DELETE_REVIEW_FAIL: "DELETE_REVIEW_FAIL",
    DELETE_REVIEW_REQUEST: "DELETE_REVIEW_REQUEST",
    DELETE_REVIEW_RESET: "DELETE_REVIEW_RESET"

}

// HOME BLOG
export const blogContants = {
    BLOG_REQUEST: 'BLOG_REQUEST',
    BLOG_SUCCESS: 'BLOG_SUCCESS',
    BLOG_FAILURE: 'BLOG_FAILURE',
    GET_SINGLE_BLOG_REQUEST: 'GET_SINGLE_BLOG_REQUEST',
    GET_SINGLE_BLOG_SUCCESS: 'GET_SINGLE_BLOG_SUCCESS',
    GET_SINGLE_BLOG_FAILURE: 'GET_SINGLE_BLOG_FAILURE'
}


// WEB-SETTING CODE START
export const settingContant = {
    GET_SINGLE_SETTING_REQUEST: 'GET_SINGLE_SETTING_REQUEST',
    GET_SINGLE_SETTING_SUCCESS: 'GET_SINGLE_SETTING_SUCCESS',
    GET_SINGLE_SETTING_FAILURE: 'GET_SINGLE_SETTING_FAILURE',
    VISION_SINGLE_SETTING_REQUEST: 'VISION_SINGLE_SETTING_REQUEST',
    VISION_SINGLE_SETTING_SUCCESS: 'VISION_SINGLE_SETTING_SUCCESS',
    VISION_SINGLE_SETTING_FAILURE: 'VISION_SINGLE_SETTING_FAILURE',
    MISION_SINGLE_SETTING_REQUEST: 'MISION_SINGLE_SETTING_REQUEST',
    MISION_SINGLE_SETTING_SUCCESS: 'MISION_SINGLE_SETTING_SUCCESS',
    MISION_SINGLE_SETTING_FAILURE: 'MISION_SINGLE_SETTING_FAILURE',
    ABOUT_SINGLE_SETTING_REQUEST: 'ABOUT_SINGLE_SETTING_REQUEST',
    ABOUT_SINGLE_SETTING_SUCCESS: 'ABOUT_SINGLE_SETTING_SUCCESS',
    ABOUT_SINGLE_SETTING_FAILURE: 'ABOUT_SINGLE_SETTING_FAILURE',
}

// CONTACT US CONTANT
export const contactContants = {
    CONTACT_REQUEST: 'CONTACT_REQUEST',
    CONTACT_SUCCESS: 'CONTACT_SUCCESS',
    CONTACT_FAILURE: 'CONTACT_FAILURE',
}


// PRODUCT CONSTANTS
export const productContant = {
    ALL_PRODUCT_REQUEST: 'ALL_PRODUCT_REQUEST',
    ALL_PRODUCT_SUCCESS: 'ALL_PRODUCT_SUCCESS',
    ALL_PRODUCT_FAIL: 'ALL_PRODUCT_FAIL',

    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAIL: 'CREATE_PRODUCT_FAIL',

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

    GET_SINGLE_PRODUCT_REQUEST: 'GET_SINGLE_PRODUCT_REQUEST',
    GET_SINGLE_PRODUCT_SUCCESS: 'GET_SINGLE_PRODUCT_SUCCESS',
    GET_SINGLE_PRODUCT_FAILURE: 'GET_SINGLE_PRODUCT_FAILURE',

    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',

}

// PRODUCT CATEGORY ROUTE
export const categoryContant = {
    ALL_CATEGORY_REQUEST: 'ALL_CATEGORY_REQUEST',
    ALL_CATEGORY_SUCCESS: 'ALL_CATEGORY_SUCCESS',
    ALL_CATEGORY_FAIL: 'ALL_CATEGORY_FAIL',


    GET_SINGLE_CATEGORY_REQUEST: 'GET_SINGLE_CATEGORY_REQUEST',
    GET_SINGLE_CATEGORY_SUCCESS: 'GET_SINGLE_CATEGORY_SUCCESS',
    GET_SINGLE_CATEGORY_FAILURE: 'GET_SINGLE_CATEGORY_FAILURE',

}

export const cartItemContant = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    SAVE_SHIPPING_INFO: "SAVE_SHIPPING_INFO"
}

export const CLEAR_ERRORS = "CLEAR_ERRORS";